all:
  children:
    seedlings:
      children:
        clients:
          children:
            desktops:
              hosts:
                192.168.1.2:
                  ansible_user: seed
            laptops:
              hosts:
                192.168.1.11:
                  ansible_user: seed
        servers:
          hosts:
            192.168.1.12:
              ansible_user: seed
            192.168.1.15:
              ansible_user: seed
    ungrouped:
      hosts:
        yggdrasil:
          ansible_host: 192.168.1.6
          ansible_port: 22
          ansible_user: forestgrowth
