- hosts: desktops
  gather_facts: true
  become: true
  vars_files:
    - ../vault.yml
  vars:
    become_user: root
    ansible_become_pass: "{{ seed_password }}"

  tasks:

    - name: Install kde-plasma
      apt:
        name: kde-plasma-desktop
        status: present
        update_cache: true

    - name: Rebooting
      reboot:

    - name: Adding config files
      copy:
        src: /etc/ansible/configs/kde/
        dest: /home/squirrel/.kde/
        directory_mode:

    - copy:
        src: /etc/ansible/configs/local/
        dest: /home/squirrel/.local/
        directory_mode:

    - copy:
        src: /etc/ansible/configs/sddm.conf
        dest: /etc/sddm.conf

    - name: Rebooting
      reboot:

