- hosts: seedlings
  gather_facts: true
  become: true
  vars_files:
    - ../vault.yml
  vars:
    ansible_become_pass: "{{ seed_password }}"

  tasks:
    
    - name: Installing utils
      apt:
        name: "['ca-certificates', 'curl', 'gnupg', 'lsb-release', 
          'net-tools', 'apt-transport-https', 'make', 'gcc', 'g++', 'xclip']"
        state: present
        update_cache: true

    - name: Installing applications
      apt:
        name: "['ranger', 'neofetch']"
        state: present
        update_cache: true
 
    - name: Installing bottom
      get_url:
        url: https://github.com/ClementTsang/bottom/releases/download/0.6.8/bottom_0.6.8_amd64.deb
        dest: /home/seed/

    - apt:
        deb: bottom_0.6.8_amd64.deb

    - file:
        state: absent
        path: bottom_0.6.8_amd64.deb

    - name: Installing neovim
      get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb
        dest: /home/seed/

    - apt:
        deb: /home/seed/nvim-linux64.deb

    - file:
        state: absent
        path: /home/seed/nvim-linux64.deb

    - name: Disable hibernation
      command: "systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target"

    - name: Purging snapd
      apt:
        name: snapd
        state: absent
        update_cache: true

    - name: Intalling drivers
      shell: "sudo ubuntu-drivers install"
