- hosts: yggdrasil
#  gather_facts: false
  become: true
  vars_files:
    - ../vault.yml
  vars:
    ansible_ssh_pass: "{{ forestgrowth_password}}"
    ansible_become_pass: "{{ forestgrowth_password }}"

  tasks:
    
    - name: Installing utils
      apt:
        name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release', 
          'net-tools', 'apt-transport-https', 'make', 'gcc', 'g++', 'xclip']
        state: present
        update_cache: true

    - name: Installing applications
      apt:
        name: ['ranger', 'neofetch']
        state: present
        update_cache: true
 
    - name: Installing bottom
      get_url:
        url: https://github.com/ClementTsang/bottom/releases/download/nightly/bottom_aarch64-unknown-linux-gnu.deb
        dest: /home/forestgrowth/

    - apt:
        deb: /home/forestgrowth/bottom_aarch64-unknown-linux-gnu.deb

    - file:
        state: absent
        path: /home/forestgrowth/bottom_aarch64-unknown-linux-gnu.deb

    - name: Disable hibernation
      command: "systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target"

    - name: Purging snapd
      apt:
        name: snapd
        state: absent
        update_cache: true
